drop table if exists brand CASCADE;
drop table if exists category CASCADE;
drop table if exists product CASCADE;
create table brand (id bigint generated by default as identity, name varchar(255), primary key (id));
create table category (id bigint generated by default as identity, name varchar(255), primary key (id));
create table product (id bigint generated by default as identity, name varchar(255), price numeric(19,2), brand_id bigint, category_id bigint, primary key (id));
alter table product add constraint FKs6cydsualtsrprvlf2bb3lcam foreign key (brand_id) references brand;
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category;
